DATA:
  data_root: /data/Datasets/ENGG5104 # modify to your own dir
  train_list: ./list/fine_train_labeled_engg5104.txt
  val_list: ./list/fine_val_engg5104.txt
  classes: 19

TRAIN:
  arch: psp
  layers: 18
  sync_bn: True  # adopt syncbn or not
  train_h: 473  
  train_w: 473
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  aux_weight: 0.4
  train_gpu: [0]
  workers: 16  # data loader workers
  batch_size: 8  # batch size for training
  batch_size_val: 1  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.005
  epochs: 100
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed:
  print_freq: 10
  save_freq: 10
  save_path: exp/cityscapes/pspnet18-aspp/model
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  use_ppm: False
  use_aspp: True
  use_ocr: False

# Distributed training is disabled by default.
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: False
  world_size: 1
  rank: 0
